SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CreateCredibleLinksForCurlWorking]  

AS

DECLARE @test nvarchar(512)
DECLARE @i int = 1

WHILE @i < 101

BEGIN


SELECT JJ.HEX_AS_ASCIIOUT AS PAYLOAD FROM
 (

  SELECT TN.IIII, SUBSTRING(TN.TBLNAM,1,LEN(TN.TBLNAM)) AS HEXSTRING, SUBSTRING(TN.TBLNAM2, @i, 3) AS HEX_AS_ASCIIOUT, @test AS TEST FROM
    (
    SELECT DISTINCT(CAST((TABLE_NAME) AS VARBINARY)) AS TBLNAM, 'THIS IS @I: ' AS PRNT, @i AS IIII, ((STUFF(CONVERT(VARCHAR(100),CAST('SELECT * FROM '+ TABLE_NAME AS VARBINARY),2 ), @i, 0, '%'))) AS TBLNAM2
    FROM Credible_Database_Schema_Columns_DataTypesSizes
    ) AS TN
) AS JJ

--SET @test = SUBSTRING(TN.TBLNAM2, @i, 3)

--SELECT 'John: ' & JJ.HEX_AS_ASCIIOUT

set @i = @i + 2

END
GO

GRANT EXECUTE ON [dbo].[CreateCredibleLinksForCurlWorking] TO [General]
GO