CREATE TABLE [dbo].[labs_procedures] (
  [Comment_Text] [varchar](500) NULL,
  [LOINC_Code] [varchar](7) NULL,
  [Test_Description] [varchar](255) NULL,
  [Test_Code] [varchar](50) NULL,
  [Report_Test_ID] [int] NULL,
  [deleted] [bit] NULL,
  [Phone_2] [varchar](50) NULL,
  [Phone_1] [varchar](50) NULL,
  [Zip] [varchar](50) NULL,
  [State] [varchar](50) NULL,
  [City] [varchar](50) NULL,
  [Street_2] [varchar](50) NULL,
  [Street_1] [varchar](50) NULL,
  [NPI_Number] [varchar](50) NULL,
  [CLIA_Number] [varchar](50) NULL,
  [Director] [varchar](200) NULL,
  [Facility_Name] [varchar](200) NULL,
  [Facility_Code] [varchar](50) NULL,
  [Facility_ID] [int] NULL,
  [Ordering_ExternalProvider_ID] [int] NULL,
  [manual_entry] [bit] NULL,
  [Fasting] [varchar](50) NULL,
  [report_accession_status] [varchar](50) NULL,
  [Sender_Order_Number] [varchar](50) NULL,
  [Placer_Order_Number] [varchar](50) NULL,
  [Practice_ID] [int] NULL,
  [Referring_Clinician_ID] [int] NULL,
  [Ordering_Clinician_ID] [int] NULL,
  [Patient_Encounter_ID] [int] NULL,
  [Patient_ID] [int] NULL,
  [Report_Accession_ID] [int] NULL,
  [Test_Type] [varchar](50) NULL,
  [Specimen_Condition] [varchar](200) NULL,
  [Specimen_Source] [varchar](200) NULL,
  [Collection_Volume] [varchar](50) NULL,
  [Action_Code] [varchar](50) NULL,
  [report_procedure_status] [varchar](50) NULL,
  [Additional_Info] [varchar](500) NULL,
  [CC_Clinician] [varchar](500) NULL,
  [Result_Date] [datetime] NULL,
  [Received_Date] [datetime] NULL,
  [Collection_Date] [datetime] NULL,
  [Report_Procedure_ID] [int] NULL
)
ON [PRIMARY]
GO