CREATE TABLE [dbo].[ClientAxisDetail] (
  [is_provisional] [bit] NULL,
  [is_42cfr] [bit] NULL,
  [is_chronic] [bit] NULL,
  [specifier_text] [varchar](250) NULL,
  [problem_list_order] [tinyint] NULL,
  [icd10_code] [varchar](8) NULL,
  [reconciled_cda] [bit] NULL,
  [final_active_client_axis_id] [int] NULL,
  [deleted] [bit] NULL,
  [snomed_cid] [bigint] NULL,
  [source] [varchar](20) NULL,
  [onset_prior_to_admission] [char](1) NULL,
  [date_resolved] [smalldatetime] NULL,
  [date_created] [datetime] NULL,
  [date_updated] [datetime] NULL,
  [updatedby_emp_id] [smallint] NULL,
  [cloned] [bit] NULL,
  [rotext] [varchar](250) NULL,
  [is_ro] [bit] NULL,
  [defaultforprograms] [varchar](500) NULL,
  [diagnosed_date] [smalldatetime] NULL,
  [diagnosed_by] [varchar](65) NULL,
  [previous_onset_date] [smalldatetime] NULL,
  [onset_date] [smalldatetime] NULL,
  [axis_code] [varchar](7) NULL,
  [axis_id] [int] NULL,
  [axisorder] [tinyint] NULL,
  [axislevel] [tinyint] NULL,
  [client_axis_id] [int] NULL,
  [clientaxisdetail_id] [int] NULL
)
ON [PRIMARY]
GO