CREATE TABLE [dbo].[Z_834_L2310_Provider_Info] (
  [zip] [varchar](15) NOT NULL,
  [temp2] [char](1) NOT NULL,
  [temp1] [char](1) NOT NULL,
  [suffix] [varchar](10) NOT NULL,
  [state] [char](2) NOT NULL,
  [provider_effective_dt] [varchar](8) NOT NULL,
  [prefix] [varchar](10) NOT NULL,
  [middlename] [varchar](25) NOT NULL,
  [maintenance_reason] [char](3) NOT NULL,
  [location_qual] [char](2) NOT NULL,
  [location_id] [varchar](30) NOT NULL,
  [lastname_or_orgname] [varchar](35) NOT NULL,
  [l2310_id] [int] NOT NULL,
  [l2000_id] [int] NOT NULL,
  [id_code_qual] [char](2) NOT NULL,
  [firstname] [varchar](25) NOT NULL,
  [entity_type_qual] [char](1) NOT NULL,
  [entity_relationship] [char](2) NOT NULL,
  [entity_id_code] [char](2) NOT NULL,
  [country] [char](3) NOT NULL,
  [contact_qual3] [char](2) NOT NULL,
  [contact_qual2] [char](2) NOT NULL,
  [contact_number3] [varchar](80) NOT NULL,
  [contact_number2] [varchar](80) NOT NULL,
  [contact_function] [char](2) NOT NULL,
  [code5_end] [char](1) NOT NULL,
  [code4_end] [char](1) NOT NULL,
  [code3_end] [char](1) NOT NULL,
  [code2_end] [char](1) NOT NULL,
  [code1_end] [char](1) NOT NULL,
  [city] [varchar](30) NOT NULL,
  [batch_id] [int] NOT NULL,
  [assigned_num] [int] NOT NULL,
  [action_code] [char](1) NOT NULL
)
ON [PRIMARY]
GO