CREATE TABLE [dbo].[ClientVisitTransportation] (
  [condition_indicator1_5] [char](2) NULL,
  [condition_indicator1_4] [char](2) NULL,
  [condition_indicator1_3] [char](2) NULL,
  [condition_indicator1_2] [char](2) NULL,
  [condition_indicator1_1] [char](2) NULL,
  [certification_condition_indicator1] [char](1) NULL,
  [ambulance_certification] [char](2) NULL,
  [stretcher_purpose_description] [varchar](80) NULL,
  [round_trip_purpose_description] [varchar](80) NULL,
  [transport_distance] [float] NULL,
  [unit_of_measurement2] [char](2) NULL,
  [ambulance_transport_reason_code] [char](1) NULL,
  [weight] [float] NULL,
  [unit_of_measurement1] [char](2) NULL,
  [dropoff_zip] [varchar](15) NULL,
  [dropoff_state] [char](2) NULL,
  [dropoff_city] [varchar](30) NULL,
  [dropoff_address_info2] [varchar](55) NULL,
  [dropoff_address_info] [varchar](55) NULL,
  [dropoff_location] [varchar](60) NULL,
  [pickup_zip] [varchar](15) NULL,
  [pickup_state] [char](2) NULL,
  [pickup_city] [varchar](30) NULL,
  [pickup_address_info2] [varchar](55) NULL,
  [pickup_address_info] [varchar](55) NULL,
  [pickup_location] [varchar](60) NULL,
  [clientvisit_id] [int] NULL
)
ON [PRIMARY]
GO