CREATE TABLE [dbo].[SearchClientsSaves] (
  [primary_only] [bit] NULL,
  [any_diagnosis] [bit] NULL,
  [axis_desc] [varchar](100) NULL,
  [icd10_code] [varchar](100) NULL,
  [axis_code] [varchar](100) NULL,
  [medcondition] [bit] NULL,
  [all_episodes] [bit] NULL,
  [enddate_use_today] [bit] NULL,
  [startdate_use_today] [bit] NULL,
  [search_team] [smallint] NULL,
  [axis3] [varchar](100) NULL,
  [axis2_id] [varchar](100) NULL,
  [axis1_id] [varchar](100) NULL,
  [group_totals_only] [bit] NULL,
  [group_totals] [bit] NULL,
  [wh_val2] [varchar](36) NULL,
  [wh_cmp2] [varchar](6) NULL,
  [wh_fld2] [varchar](100) NULL,
  [wh_andor] [varchar](4) NULL,
  [wh_val1] [varchar](36) NULL,
  [wh_cmp1] [varchar](6) NULL,
  [wh_fld1] [varchar](100) NULL,
  [sort_order2] [bit] NULL,
  [sort_order] [bit] NULL,
  [sortby2] [varchar](100) NULL,
  [sortby] [varchar](100) NULL,
  [global_view] [bit] NULL,
  [default_view] [bit] NULL,
  [multi_line] [bit] NULL,
  [non_billable] [tinyint] NULL,
  [payer_id2] [smallint] NULL,
  [client_status] [varchar](20) NULL,
  [emp_id] [smallint] NULL,
  [save_date] [smalldatetime] NULL,
  [save_name] [varchar](30) NULL,
  [searchclientssaves_id] [int] NULL
)
ON [PRIMARY]
GO