CREATE TABLE [dbo].[ImportAuthorizations] (
  [credential_group] [varchar](12) NULL,
  [auth_level] [varchar](50) NULL,
  [visittype_id15] [smallint] NULL,
  [visittype_id14] [smallint] NULL,
  [visittype_id13] [smallint] NULL,
  [visittype_id12] [smallint] NULL,
  [visittype_id11] [smallint] NULL,
  [visittype_id10] [smallint] NULL,
  [visittype_id9] [smallint] NULL,
  [visittype_id8] [smallint] NULL,
  [visittype_id7] [smallint] NULL,
  [visittype_id6] [smallint] NULL,
  [visittype_id5] [smallint] NULL,
  [visittype_id4] [smallint] NULL,
  [visittype_id3] [smallint] NULL,
  [visittype_id2] [smallint] NULL,
  [visittype_id1] [smallint] NULL,
  [visittype_group] [varchar](25) NULL,
  [count_units] [tinyint] NULL,
  [ext_units_used] [decimal] NULL,
  [auth_units] [decimal] NULL,
  [period_end] [smalldatetime] NULL,
  [period_start] [smalldatetime] NULL,
  [auth_date] [smalldatetime] NULL,
  [program_id] [smallint] NULL,
  [location_id] [smallint] NULL,
  [payer_id] [smallint] NULL,
  [client_id] [int] NULL,
  [auth_number] [varchar](50) NULL,
  [external_id] [varchar](12) NULL
)
ON [PRIMARY]
GO