CREATE TABLE [dbo].[Z_834_L2100B_Incorrect_Member_Name] (
  [code2_end] [char](1) NULL,
  [citzenship_status] [char](2) NULL,
  [race_end] [char](1) NULL,
  [industry_code] [varchar](30) NULL,
  [ethnicity] [char](3) NULL,
  [race] [char](1) NULL,
  [race_start] [char](1) NULL,
  [maritial_status] [char](1) NULL,
  [gender] [char](1) NULL,
  [dob] [varchar](8) NULL,
  [dt_format_qual] [char](2) NULL,
  [code2] [char](3) NULL,
  [code1_end] [char](1) NULL,
  [id_code] [varchar](80) NULL,
  [id_code_qual] [char](2) NULL,
  [suffix] [varchar](10) NULL,
  [prefix] [varchar](10) NULL,
  [middlename] [varchar](25) NULL,
  [firstname] [varchar](35) NULL,
  [lastname] [varchar](60) NULL,
  [entity_type_qual] [char](1) NULL,
  [entity_id_code] [char](2) NULL,
  [code1] [char](3) NULL,
  [l2000_id] [int] NULL,
  [batch_id] [int] NULL,
  [l2100b_id] [int] NULL
)
ON [PRIMARY]
GO