CREATE TABLE [dbo].[Icd9CMMasterToSNOMEDMap] (
  [in_core] [bit] NULL,
  [core_usage] [numeric] NULL,
  [is_1-1map] [bit] NULL,
  [snomed_fsn] [varchar](500) NULL,
  [snomed_cid] [bigint] NULL,
  [is_nec] [bit] NULL,
  [avg_usage] [numeric] NULL,
  [op_usage] [numeric] NULL,
  [ip_usage] [numeric] NULL,
  [is_current_icd] [bit] NULL,
  [icd9_name] [varchar](500) NULL,
  [icd9_desc_alt] [varchar](100) NULL,
  [l5head] [bit] NULL,
  [l4head] [bit] NULL,
  [l3head] [bit] NULL,
  [l2head] [bit] NULL,
  [l1head] [bit] NULL,
  [icd9_notes] [varchar](500) NULL,
  [group_notes] [varchar](500) NULL,
  [major_notes] [varchar](500) NULL,
  [diagnosis_code] [varchar](6) NULL,
  [common] [bit] NULL,
  [group_desc] [varchar](100) NULL,
  [group_code] [varchar](10) NULL,
  [icd9_desc_long] [varchar](255) NULL,
  [icd9_desc] [varchar](100) NULL,
  [major_desc] [varchar](100) NULL,
  [major_code] [varchar](10) NULL,
  [icd9_code] [varchar](7) NULL
)
ON [PRIMARY]
GO