CREATE TABLE [dbo].[ImportClientAxis] (
  [termination_date] [smalldatetime] NOT NULL,
  [effective_date] [smalldatetime] NOT NULL,
  [client_id] [int] NOT NULL,
  [axis_5_current] [smallint] NOT NULL,
  [axis_4_text] [varchar](512) NOT NULL,
  [axis_3_code_e] [varchar](7) NOT NULL,
  [axis_3_code_d] [varchar](7) NOT NULL,
  [axis_3_code_c] [varchar](7) NOT NULL,
  [axis_3_code_b] [varchar](7) NOT NULL,
  [axis_3_code_a] [varchar](7) NOT NULL,
  [axis_2b_ro] [bit] NOT NULL,
  [axis_2b_diagnosed_by] [varchar](50) NOT NULL,
  [axis_2a_ro] [bit] NOT NULL,
  [axis_2a_diagnosed_by] [varchar](50) NOT NULL,
  [axis_2_code_b] [varchar](6) NOT NULL,
  [axis_2_code_a] [varchar](6) NOT NULL,
  [axis_1e_ro] [bit] NOT NULL,
  [axis_1e_diagnosed_by] [varchar](50) NOT NULL,
  [axis_1d_ro] [bit] NOT NULL,
  [axis_1d_diagnosed_by] [varchar](50) NOT NULL,
  [axis_1c_ro] [bit] NOT NULL,
  [axis_1c_diagnosed_by] [varchar](50) NOT NULL,
  [axis_1b_ro] [bit] NOT NULL,
  [axis_1b_diagnosed_by] [varchar](50) NOT NULL,
  [axis_1a_ro] [bit] NOT NULL,
  [axis_1a_diagnosed_by] [varchar](50) NOT NULL,
  [axis_1_code_f] [varchar](6) NOT NULL,
  [axis_1_code_e] [varchar](6) NOT NULL,
  [axis_1_code_d] [varchar](6) NOT NULL,
  [axis_1_code_c] [varchar](6) NOT NULL,
  [axis_1_code_b] [varchar](6) NOT NULL,
  [axis_1_code_a] [varchar](6) NOT NULL
)
ON [PRIMARY]
GO