CREATE TABLE [dbo].[Z_Payment] (
  [allow_duplicate_checkno] [bit] NULL,
  [cc_payment] [bit] NULL,
  [updatedby_emp_id] [smallint] NULL,
  [date_updated] [datetime] NULL,
  [revenuecode_id] [int] NULL,
  [paymentcontrol_id] [int] NULL,
  [payment_category] [varchar](50) NULL,
  [payment_location] [varchar](50) NULL,
  [return_date] [smalldatetime] NULL,
  [deposit_date] [smalldatetime] NULL,
  [load835_id] [int] NULL,
  [check_received] [bit] NULL,
  [date_closed] [smalldatetime] NULL,
  [date_entered] [smalldatetime] NULL,
  [notes] [varchar](1024) NULL,
  [retracted_services] [int] NULL,
  [balance] [decimal] NULL,
  [retracted_amount] [decimal] NULL,
  [retraction_amount] [decimal] NULL,
  [adjusted_amount] [decimal] NULL,
  [paid_amount] [decimal] NULL,
  [paid_services] [int] NULL,
  [paid_claims] [int] NULL,
  [status] [varchar](10) NULL,
  [check_date] [smalldatetime] NULL,
  [amount] [decimal] NULL,
  [check_num] [varchar](50) NULL,
  [ref_num] [varchar](20) NULL,
  [payment_type] [varchar](10) NULL,
  [client_id] [int] NULL,
  [payer_desc] [varchar](50) NULL,
  [payer_id] [smallint] NULL,
  [emp_id] [smallint] NULL,
  [payment_id] [int] NULL
)
ON [PRIMARY]
GO