CREATE TABLE [dbo].[ClientLiability] (
  [updatedby_emp_id] [smallint] NOT NULL,
  [update_mode] [int] NOT NULL,
  [unverified_income_reason] [smallint] NOT NULL,
  [total_slide] [decimal] NOT NULL,
  [total_allowable_expenses_monthly] [decimal] NOT NULL,
  [total_allowable_expenses_annually] [decimal] NOT NULL,
  [tfi_yearly] [bit] NOT NULL,
  [suppress_print_reason] [smallint] NOT NULL,
  [start_date] [date] NOT NULL,
  [slide_start_date] [date] NOT NULL,
  [slide_percentage] [decimal] NOT NULL,
  [slide_end_date] [date] NOT NULL,
  [skip_form] [bit] NOT NULL,
  [real_estate_tax] [decimal] NOT NULL,
  [program_type] [smallint] NOT NULL,
  [program_id] [smallint] NOT NULL,
  [other_deduct2] [decimal] NOT NULL,
  [other_deduct1] [decimal] NOT NULL,
  [medical_expenses_monthly] [decimal] NOT NULL,
  [medical_expenses_grossincome_monthly] [decimal] NOT NULL,
  [medical_expenses_grossincome_annually] [decimal] NOT NULL,
  [client_id] [int] NOT NULL,
  [medical_exp_source5] [varchar](50) NOT NULL,
  [medical_exp_source4] [varchar](50) NOT NULL,
  [medical_exp_source3] [varchar](50) NOT NULL,
  [medical_exp_source2] [varchar](50) NOT NULL,
  [change_date] [date] NOT NULL,
  [medical_exp_ins] [decimal] NOT NULL,
  [medical_exp_amount5] [decimal] NOT NULL,
  [medical_exp_amount4] [decimal] NOT NULL,
  [medical_exp_amount3] [decimal] NOT NULL,
  [medical_exp_amount2] [decimal] NOT NULL
)
ON [PRIMARY]
GO