CREATE TABLE [dbo].[Z_EDI_L2010AB_Pay_To_Provider_name] (
  [zip] [varchar](15) NOT NULL,
  [suffix] [varchar](10) NOT NULL,
  [state] [char](2) NOT NULL,
  [reference_id_qual3] [char](3) NOT NULL,
  [reference_id_qual2] [char](3) NOT NULL,
  [prefix] [varchar](10) NOT NULL,
  [pay_to_provider_additional_id3] [varchar](30) NOT NULL,
  [pay_to_provider_additional_id2] [varchar](30) NOT NULL,
  [middle_name] [varchar](25) NOT NULL,
  [location_qual] [char](1) NOT NULL,
  [location_id] [char](1) NOT NULL,
  [last_name_or_org] [varchar](60) NOT NULL,
  [l2010ab_id] [int] NOT NULL,
  [l2000a_id] [int] NOT NULL,
  [id_code_qual] [varchar](2) NOT NULL,
  [first_name] [varchar](25) NOT NULL,
  [entity_type_qual] [int] NOT NULL,
  [entity_id_code] [char](3) NOT NULL,
  [country_sub_code] [char](3) NOT NULL,
  [country_code] [char](3) NOT NULL,
  [code6_end] [char](1) NOT NULL,
  [code5_end] [char](1) NOT NULL,
  [code4_end] [char](1) NOT NULL,
  [code3_end] [char](1) NOT NULL,
  [code2_end] [char](1) NOT NULL,
  [code1_end] [char](1) NOT NULL,
  [city] [varchar](30) NOT NULL,
  [batch_id] [int] NOT NULL,
  [address_info2] [varchar](55) NOT NULL
)
ON [PRIMARY]
GO