CREATE TABLE [dbo].[Z_834_L2300_Health_Coverage] (
  [code5_end] [char](1) NULL,
  [action_code] [char](2) NULL,
  [id_card_count] [int] NULL,
  [id_card_type] [char](1) NULL,
  [plan_coverage_desc2] [varchar](50) NULL,
  [code5] [char](3) NULL,
  [code4_end] [char](1) NULL,
  [policy_number] [varchar](30) NULL,
  [ref_id_qual] [char](2) NULL,
  [code4] [char](3) NULL,
  [code3_end] [char](1) NULL,
  [contract_amount] [varchar](18) NULL,
  [amount_qual] [char](2) NULL,
  [code3] [char](3) NULL,
  [code2b_end] [char](1) NULL,
  [coverage_periodb] [varchar](35) NULL,
  [dt_format_qualb] [char](2) NULL,
  [dt_qualb] [char](3) NULL,
  [code2b] [char](3) NULL,
  [code2a_end] [char](1) NULL,
  [coverage_perioda] [varchar](35) NULL,
  [dt_format_quala] [char](2) NULL,
  [dt_quala] [char](3) NULL,
  [code2a] [char](3) NULL,
  [code2_end] [char](1) NULL,
  [coverage_period] [varchar](35) NULL,
  [dt_format_qual] [char](2) NULL,
  [dt_qual] [char](3) NULL,
  [code2] [char](3) NULL,
  [code1_end] [char](1) NULL,
  [coverage_level] [char](3) NULL,
  [plan_coverage_desc] [varchar](50) NULL,
  [insurance_line] [char](3) NULL,
  [temp1] [char](1) NULL,
  [maintenance_type] [char](3) NULL,
  [code1] [char](2) NULL,
  [l2000_id] [int] NULL,
  [batch_id] [int] NULL,
  [l2300_id] [int] NULL
)
ON [PRIMARY]
GO