CREATE TABLE [dbo].[MedSchedule] (
  [emarpatientresponse_id] [int] NULL,
  [suspended] [bit] NULL,
  [med_admin_reconciliation_id] [int] NULL,
  [unused_med_reason] [int] NULL,
  [unused_med_count] [decimal] NULL,
  [refill_count] [decimal] NULL,
  [methasoft_ndc] [varchar](11) NULL,
  [visittemp_id] [int] NULL,
  [route_time] [nvarchar](100) NULL,
  [frequency] [nvarchar](100) NULL,
  [medschedulerecurrence_id] [int] NULL,
  [med_schedule_version] [tinyint] NULL,
  [external_id] [varchar](50) NULL,
  [date_pillbox_reconciled] [datetime] NULL,
  [emarpillbox_id] [int] NULL,
  [updated_date] [datetime] NULL,
  [updated_by_emp_id] [smallint] NULL,
  [dosage_note] [varchar](500) NULL,
  [pill_count] [decimal] NULL,
  [prn_interval] [tinyint] NULL,
  [stat] [bit] NULL,
  [prn] [bit] NULL,
  [medscheduledata_id] [int] NULL,
  [medinventory_id] [int] NULL,
  [create_date] [datetime] NULL,
  [qty_administered] [decimal] NULL,
  [refusal_reason] [varchar](100) NULL,
  [patient_response] [varchar](20) NULL,
  [injection_site] [varchar](50) NULL,
  [did_patient_take] [bit] NULL,
  [dispensed_verified_by_emp_id] [smallint] NULL,
  [dispensed_by_emp_id] [smallint] NULL,
  [dispensed_on] [datetime] NULL,
  [dispensed] [bit] NULL,
  [route_string] [varchar](50) NULL,
  [dosage_quantity] [varchar](25) NULL,
  [dosage_action_string] [varchar](50) NULL,
  [dosage] [varchar](40) NULL,
  [dispense_on] [datetime] NULL,
  [created_by_emp_id] [smallint] NULL,
  [med_id] [int] NULL,
  [schedule_id] [int] NULL
)
ON [PRIMARY]
GO