CREATE TABLE [dbo].[ClientVisitDiagnosis] (
  [reason_for_visit_icd10_code3] [varchar](8) NOT NULL,
  [reason_for_visit_icd10_code2] [varchar](8) NOT NULL,
  [reason_for_visit_icd10_code1] [varchar](8) NOT NULL,
  [onset_prior_to_admission9] [char](1) NOT NULL,
  [onset_prior_to_admission8] [char](1) NOT NULL,
  [onset_prior_to_admission7] [char](1) NOT NULL,
  [onset_prior_to_admission6] [char](1) NOT NULL,
  [onset_prior_to_admission5] [char](1) NOT NULL,
  [onset_prior_to_admission4] [char](1) NOT NULL,
  [onset_prior_to_admission3] [char](1) NOT NULL,
  [onset_prior_to_admission2] [char](1) NOT NULL,
  [onset_prior_to_admission12] [char](1) NOT NULL,
  [onset_prior_to_admission11] [char](1) NOT NULL,
  [onset_prior_to_admission10] [char](1) NOT NULL,
  [ECI_icd10_code9] [varchar](8) NOT NULL,
  [ECI_icd10_code8] [varchar](8) NOT NULL,
  [ECI_icd10_code7] [varchar](8) NOT NULL,
  [ECI_icd10_code6] [varchar](8) NOT NULL,
  [ECI_icd10_code5] [varchar](8) NOT NULL,
  [ECI_icd10_code4] [varchar](8) NOT NULL,
  [ECI_icd10_code3] [varchar](8) NOT NULL,
  [ECI_icd10_code2] [varchar](8) NOT NULL,
  [ECI_icd10_code12] [varchar](8) NOT NULL,
  [ECI_icd10_code11] [varchar](8) NOT NULL,
  [ECI_icd10_code10] [varchar](8) NOT NULL,
  [clientvisit_id] [int] NOT NULL
)
ON [PRIMARY]
GO