CREATE TABLE [dbo].[Z_EligibilityInfo] (
  [eligible_provider] [varchar](60) NULL,
  [pcp_name] [varchar](60) NULL,
  [subscriber_benefit_contactnum2] [varchar](50) NULL,
  [subscriber_benefit_contacttype2] [char](2) NULL,
  [subscriber_benefit_contactnum1] [varchar](50) NULL,
  [subscriber_benefit_contacttype1] [char](2) NULL,
  [subscriber_benefit_person] [varchar](60) NULL,
  [other_id_qual] [char](3) NULL,
  [other_id] [varchar](30) NULL,
  [ins_id] [varchar](25) NULL,
  [payer_name] [varchar](60) NULL,
  [message] [varchar](264) NULL,
  [delivery_shipment_time] [char](1) NULL,
  [delivery_shipment_pattern] [char](2) NULL,
  [delivery_num_periods] [char](3) NULL,
  [delivery_time_qual] [char](2) NULL,
  [delivery_sample] [varchar](6) NULL,
  [delivery_measurement] [char](2) NULL,
  [delivery_quantity] [varchar](15) NULL,
  [delivery_quantity_qual] [char](2) NULL,
  [procedure_indentifier] [varchar](150) NULL,
  [in_plan_network_indicator] [char](1) NULL,
  [certification_indicator] [char](1) NULL,
  [benefit_quantity] [varchar](15) NULL,
  [quantity_qual] [char](2) NULL,
  [benefit_percent] [varchar](50) NULL,
  [monetary_amount] [varchar](20) NULL,
  [time_qual] [char](2) NULL,
  [plan_coverage] [varchar](50) NULL,
  [insurance_type] [varchar](250) NULL,
  [service_type] [varchar](250) NULL,
  [coverage_level] [char](3) NULL,
  [benefit_information] [char](2) NULL,
  [rejection_follow_up] [char](1) NULL,
  [rejection_reason_code] [char](2) NULL,
  [rejection_indication] [char](1) NULL,
  [eligible] [bit] NULL,
  [eligibility_id] [int] NULL,
  [eligibilityinfo_id] [int] NULL
)
ON [PRIMARY]
GO