CREATE TABLE [dbo].[ClinicalSupport] (
  [is_video] [bit] NULL,
  [is_education] [bit] NULL,
  [priority] [smallint] NULL,
  [clinicalsupport_group] [varchar](20) NULL,
  [data_dict_value_to] [varchar](500) NULL,
  [data_dict_value_from] [varchar](500) NULL,
  [data_dict_id_2] [int] NULL,
  [weight_to] [float] NULL,
  [weight_from] [float] NULL,
  [height_in_to] [float] NULL,
  [height_ft_to] [tinyint] NULL,
  [height_in_from] [float] NULL,
  [height_ft_from] [tinyint] NULL,
  [bp_bottom_to] [smallint] NULL,
  [bp_top_to] [smallint] NULL,
  [bp_bottom_from] [smallint] NULL,
  [bp_top_from] [smallint] NULL,
  [bp_type] [smallint] NULL,
  [release] [varchar](250) NULL,
  [funding_source] [varchar](500) NULL,
  [developer] [varchar](500) NULL,
  [updatedby_emp_id] [smallint] NULL,
  [is_deleted] [bit] NULL,
  [updated_by_emp_id] [int] NULL,
  [date_updated] [datetime] NULL,
  [date_created] [datetime] NULL,
  [summary] [varchar](150) NULL,
  [file_id] [int] NULL,
  [url] [varchar](550) NULL,
  [push_to_client] [bit] NULL,
  [data_dict_value] [varchar](500) NULL,
  [data_dict_id] [int] NULL,
  [age_max] [int] NULL,
  [age_min] [int] NULL,
  [sex] [char](1) NULL,
  [max_lab_result] [decimal] NULL,
  [min_lab_result] [decimal] NULL,
  [clinicalsupport_id] [int] NULL
)
ON [PRIMARY]
GO