CREATE TABLE [dbo].[ClientMedicalProfileImmunization] (
  [vac_info_presented] [datetime] NOT NULL,
  [vac_info_date] [datetime] NOT NULL,
  [vac_fund_src] [varchar](100) NOT NULL,
  [vac_fund_prog_cat] [varchar](50) NOT NULL,
  [updatedby_emp_id] [int] NOT NULL,
  [units] [varchar](50) NOT NULL,
  [substance_exp_date] [datetime] NOT NULL,
  [route_of_admin] [varchar](50) NOT NULL,
  [ordered_by] [varchar](100) NOT NULL,
  [ndc] [varchar](11) NOT NULL,
  [manu_name] [varchar](120) NOT NULL,
  [manu_code] [varchar](50) NOT NULL,
  [lot_num] [varchar](50) NOT NULL,
  [lookup_id] [varchar](10) NOT NULL,
  [is_deleted] [bit] NOT NULL,
  [information_source] [varchar](50) NOT NULL,
  [immunization_resistance] [varchar](50) NOT NULL,
  [immune_id] [int] NOT NULL,
  [immune_date] [datetime] NOT NULL,
  [dosage_amount] [varchar](20) NOT NULL,
  [deletedby_emp_id] [int] NOT NULL,
  [date_updated_utc] [datetime] NOT NULL,
  [date_deleted_utc] [datetime] NOT NULL,
  [date_created_utc] [datetime] NOT NULL,
  [createdby_emp_id] [int] NOT NULL,
  [clientmedicalprofile_id] [int] NOT NULL,
  [client_id] [int] NOT NULL,
  [admin_site] [varchar](50) NOT NULL,
  [admin_provider] [varchar](100) NOT NULL,
  [admin_location] [varchar](200) NOT NULL
)
ON [PRIMARY]
GO