CREATE TABLE [dbo].[Z_834_L2320_COB] (
  [code5_end] [char](1) NULL,
  [cob_dt2] [varchar](35) NULL,
  [dt_format_qual2] [char](2) NULL,
  [dt_qual2] [char](3) NULL,
  [code5] [char](3) NULL,
  [code4_end] [char](1) NULL,
  [cob_dt] [varchar](35) NULL,
  [dt_format_qual] [char](2) NULL,
  [dt_qual] [char](3) NULL,
  [code4] [char](3) NULL,
  [code3_end] [char](1) NULL,
  [id_code] [varchar](80) NULL,
  [id_code_qual] [char](2) NULL,
  [insurer_name] [varchar](60) NULL,
  [entity_id_code] [char](2) NULL,
  [code3] [char](2) NULL,
  [code2_end] [char](1) NULL,
  [policy_number2] [varchar](30) NULL,
  [ref_id_qual] [char](3) NULL,
  [code2] [char](3) NULL,
  [code1_end] [char](1) NULL,
  [cob_code] [char](1) NULL,
  [policy_number] [varchar](30) NULL,
  [payer_responsibility_seq_num] [char](1) NULL,
  [code1] [char](3) NULL,
  [l2000_id] [int] NULL,
  [batch_id] [int] NULL,
  [l2320_id] [int] NULL
)
ON [PRIMARY]
GO