CREATE TABLE [dbo].[Z_CMS_byemployee] (
  [totalcharge_box28] [decimal] NOT NULL,
  [cmsclaimtemp_id] [int] NOT NULL,
  [batch_id] [int] NOT NULL,
  [balancedue_box30] [decimal] NOT NULL,
  [amountpaid_box29] [decimal] NOT NULL,
  [diagnosis8_box21] [varchar](8) NOT NULL,
  [unabletoworkfrom_box16] [datetime] NOT NULL,
  [diagnosis6_box21] [varchar](8) NOT NULL,
  [diagnosis5_2012_box21] [varchar](8) NOT NULL,
  [diagnosis4_box21] [varchar](8) NOT NULL,
  [servicefacilitylocationstate_box32] [char](3) NOT NULL,
  [diagnosis3_box21] [varchar](8) NOT NULL,
  [diagnosis3_2012_box21] [varchar](8) NOT NULL,
  [diagnosis2_box21] [varchar](8) NOT NULL,
  [servicefacilitylocationname_box32] [varchar](50) NOT NULL,
  [diagnosis12_box21] [varchar](8) NOT NULL,
  [diagnosis11_box21] [varchar](8) NOT NULL,
  [diagnosis10_box21] [varchar](8) NOT NULL,
  [diagnosis1_box21] [varchar](8) NOT NULL,
  [referringprovideridqual_box17b] [char](2) NOT NULL,
  [billingproviderphone_box33] [varchar](10) NOT NULL,
  [billingprovidername_box33] [varchar](50) NOT NULL,
  [billingproviderlocationstate_box33] [char](3) NOT NULL,
  [qualifier_2012_saveillnessdate_box15] [varchar](3) NOT NULL,
  [billingproviderlocationnzip_box33] [varchar](10) NOT NULL,
  [billingproviderlocationnpi_box33a] [varchar](10) NOT NULL,
  [billingproviderlocationcity_box33] [varchar](30) NOT NULL,
  [qualifier_2012_icdind_box21] [varchar](1) NOT NULL,
  [billingprovideraddress_box33] [varchar](101) NOT NULL,
  [physician_id] [int] NOT NULL,
  [acceptassignment_box27] [char](1) NOT NULL
)
ON [PRIMARY]
GO