CREATE TABLE [dbo].[NotificationEvent] (
  [order_creator] [bit] NULL,
  [columnname2] [varchar](50) NULL,
  [columnvalue2] [varchar](50) NULL,
  [specified_id6] [int] NULL,
  [specified_id5] [int] NULL,
  [specified_id4] [int] NULL,
  [specified_id3] [int] NULL,
  [scheduled_emp] [bit] NULL,
  [assignment] [bit] NULL,
  [emargroup_id] [smallint] NULL,
  [specifiedteam_id] [smallint] NULL,
  [updatedby_emp_id] [smallint] NULL,
  [date_updated] [smalldatetime] NULL,
  [todolist] [bit] NULL,
  [credential_id] [int] NULL,
  [specified_id2] [int] NULL,
  [role_id] [smallint] NULL,
  [specifiedemp_id] [smallint] NULL,
  [profile_code] [varchar](12) NULL,
  [deleted_by] [smallint] NULL,
  [date_deleted] [smalldatetime] NULL,
  [deleted] [bit] NULL,
  [created_by] [smallint] NULL,
  [date_created] [smalldatetime] NULL,
  [specified_id] [int] NULL,
  [columnvalue] [varchar](250) NULL,
  [columnname] [varchar](50) NULL,
  [predefined] [bit] NULL,
  [mustdismiss] [bit] NULL,
  [sendto] [varchar](10) NULL,
  [sendemail] [bit] NULL,
  [occurdays] [smallint] NULL,
  [occuronce] [bit] NULL,
  [reminddays] [smallint] NULL,
  [sendreminder] [bit] NULL,
  [title] [varchar](150) NULL,
  [type_id] [int] NULL,
  [type] [char](1) NULL,
  [trigger_id] [smallint] NULL,
  [is_trigger] [bit] NULL,
  [notificationevent_id] [int] NULL
)
ON [PRIMARY]
GO