CREATE TABLE [dbo].[ClientDependent] (
  [zip] [varchar](10) NOT NULL,
  [state] [varchar](3) NOT NULL,
  [source] [varchar](10) NOT NULL,
  [ROI_dimensions] [varchar](500) NOT NULL,
  [ROI_billing] [bit] NOT NULL,
  [ROI_42cfr] [bit] NOT NULL,
  [rights_terminated] [bit] NOT NULL,
  [removed_from_home] [bit] NOT NULL,
  [relation_type] [varchar](25) NOT NULL,
  [primary_care_giver] [bit] NOT NULL,
  [phone2] [varchar](25) NOT NULL,
  [Mobile_VisitDestAddress] [bit] NOT NULL,
  [living_at_home] [bit] NOT NULL,
  [is_guarantor] [bit] NOT NULL,
  [is_dependent] [bit] NOT NULL,
  [info_release_start] [smalldatetime] NOT NULL,
  [info_release_expire] [smalldatetime] NOT NULL,
  [guarantor_start] [smalldatetime] NOT NULL,
  [guarantor_end] [smalldatetime] NOT NULL,
  [enrolled_with_vo] [bit] NOT NULL,
  [dob] [datetime] NOT NULL,
  [dependentclient_id] [int] NOT NULL,
  [dependent_name] [varchar](50) NOT NULL,
  [dependent_id] [int] NOT NULL,
  [date_updated] [datetime] NOT NULL,
  [date_of_death] [datetime] NOT NULL,
  [date_created] [datetime] NOT NULL,
  [client_name] [varchar](150) NOT NULL,
  [city] [varchar](50) NOT NULL,
  [age] [int] NOT NULL,
  [address2] [varchar](50) NOT NULL,
  [address1] [varchar](50) NOT NULL
)
ON [PRIMARY]
GO