CREATE TABLE [dbo].[NotificationTrigger] (
  [specifyid6] [varchar](50) NULL,
  [specifyname6] [varchar](50) NULL,
  [specifylabel6] [varchar](50) NULL,
  [can_specify_id6] [bit] NULL,
  [specifyid5] [varchar](50) NULL,
  [specifyname5] [varchar](50) NULL,
  [specifylabel5] [varchar](50) NULL,
  [can_specify_id5] [bit] NULL,
  [specifyid4] [varchar](50) NULL,
  [specifyname4] [varchar](50) NULL,
  [specifylabel4] [varchar](50) NULL,
  [can_specify_id4] [bit] NULL,
  [updatedby_emp_id] [smallint] NULL,
  [date_updated] [smalldatetime] NULL,
  [specifyid3] [varchar](50) NULL,
  [specifyname3] [varchar](50) NULL,
  [specifylabel3] [varchar](50) NULL,
  [can_specify_id3] [bit] NULL,
  [specifyid2] [varchar](50) NULL,
  [specifyname2] [varchar](50) NULL,
  [specifylabel2] [varchar](50) NULL,
  [can_specify_id2] [bit] NULL,
  [specifyid] [varchar](50) NULL,
  [specifyname] [varchar](50) NULL,
  [specifylabel] [varchar](50) NULL,
  [can_specify_id] [bit] NULL,
  [can_be_specific] [bit] NULL,
  [type] [char](1) NULL,
  [description] [varchar](50) NULL,
  [notificationtrigger_id] [smallint] NULL
)
ON [PRIMARY]
GO