CREATE TABLE [dbo].[ClientDependent] (
  [Mobile_VisitDestAddress] [bit] NULL,
  [ROI_42cfr] [bit] NULL,
  [ROI_billing] [bit] NULL,
  [ROI_dimensions] [varchar](500) NULL,
  [age] [int] NULL,
  [date_of_death] [datetime] NULL,
  [guarantor_end] [smalldatetime] NULL,
  [guarantor_start] [smalldatetime] NULL,
  [source] [varchar](10) NULL,
  [phone2] [varchar](25) NULL,
  [info_release_expire] [smalldatetime] NULL,
  [info_release_start] [smalldatetime] NULL,
  [info_release] [bit] NULL,
  [date_updated] [datetime] NULL,
  [date_created] [datetime] NULL,
  [rights_terminated] [bit] NULL,
  [primary_care_giver] [bit] NULL,
  [phone] [varchar](25) NULL,
  [zip] [varchar](10) NULL,
  [state] [varchar](3) NULL,
  [city] [varchar](50) NULL,
  [address2] [varchar](50) NULL,
  [address1] [varchar](50) NULL,
  [is_guarantor] [bit] NULL,
  [removed_from_home] [bit] NULL,
  [living_at_home] [bit] NULL,
  [enrolled_with_vo] [bit] NULL,
  [dependent_name] [varchar](50) NULL,
  [client_name] [varchar](150) NULL,
  [dob] [datetime] NULL,
  [is_dependent] [bit] NULL,
  [relation_type] [varchar](25) NULL,
  [dependentclient_id] [int] NULL,
  [client_id] [int] NULL,
  [dependent_id] [int] NULL
)
ON [PRIMARY]
GO