CREATE TABLE [dbo].[ExportBuilder] (
  [is_running] [bit] NULL,
  [form_type] [int] NULL,
  [can_delete] [bit] NULL,
  [edi_config_id] [smallint] NULL,
  [require_ws_auth] [bit] NULL,
  [col_to_update] [varchar](25) NULL,
  [is_advsearch] [bit] NULL,
  [updatedby_emp_id] [smallint] NULL,
  [date_updated] [datetime] NULL,
  [is_locked] [bit] NULL,
  [created_by_emp_id] [smallint] NULL,
  [is_report_tab] [bit] NULL,
  [use_row_security] [bit] NULL,
  [is_dd_table] [bit] NULL,
  [primary_key] [varchar](50) NULL,
  [custom_report] [varchar](50) NULL,
  [dd_desc_col3] [varchar](50) NULL,
  [dd_id_col3] [varchar](50) NULL,
  [dd_sql3] [varchar](500) NULL,
  [dd_desc_col2] [varchar](50) NULL,
  [dd_id_col2] [varchar](50) NULL,
  [dd_sql2] [varchar](500) NULL,
  [dd_desc_col1] [varchar](50) NULL,
  [dd_id_col1] [varchar](50) NULL,
  [dd_sql1] [varchar](500) NULL,
  [custom_param3] [varchar](25) NULL,
  [custom_param2] [varchar](25) NULL,
  [custom_param1] [varchar](25) NULL,
  [last_run] [smalldatetime] NULL,
  [date_created] [smalldatetime] NULL,
  [date_format] [varchar](20) NULL,
  [export_table_num] [int] NULL,
  [clear_export_table] [bit] NULL,
  [for_print] [bit] NULL,
  [batch_mode] [bit] NULL,
  [quoted_fields] [bit] NULL,
  [delimiter] [varchar](3) NULL,
  [output_format] [varchar](5) NULL,
  [is_empform] [bit] NULL,
  [form_ver_id] [int] NULL,
  [form_name] [varchar](50) NULL,
  [form_id] [smallint] NULL,
  [export_name] [varchar](50) NULL,
  [exportbuilder_id] [smallint] NULL
)
ON [PRIMARY]
GO