CREATE TABLE [dbo].[ClientMedicalProfileImmunization] (
  [date_deleted_utc] [datetime] NULL,
  [deletedby_emp_id] [int] NULL,
  [is_deleted] [bit] NULL,
  [ndc] [varchar](11) NULL,
  [information_source] [varchar](50) NULL,
  [immunization_resistance] [varchar](50) NULL,
  [date_updated_utc] [datetime] NULL,
  [date_updated] [datetime] NULL,
  [date_created_utc] [datetime] NULL,
  [date_created] [datetime] NULL,
  [updatedby_emp_id] [int] NULL,
  [createdby_emp_id] [int] NULL,
  [dosage_amount] [varchar](20) NULL,
  [substance_exp_date] [datetime] NULL,
  [vac_fund_src] [varchar](100) NULL,
  [vac_fund_prog_cat] [varchar](50) NULL,
  [vac_info_presented] [datetime] NULL,
  [vac_info_date] [datetime] NULL,
  [admin_site] [varchar](50) NULL,
  [route_of_admin] [varchar](50) NULL,
  [admin_location] [varchar](200) NULL,
  [admin_provider] [varchar](100) NULL,
  [ordered_by] [varchar](100) NULL,
  [units] [varchar](50) NULL,
  [manu_code] [varchar](50) NULL,
  [manu_name] [varchar](120) NULL,
  [lot_num] [varchar](50) NULL,
  [dosage] [varchar](50) NULL,
  [immune_date] [datetime] NULL,
  [lookup_id] [varchar](10) NULL,
  [clientmedicalprofile_id] [int] NULL,
  [client_id] [int] NULL,
  [immune_id] [int] NULL
)
ON [PRIMARY]
GO