CREATE TABLE [dbo].[ClientVisitClaimNote] (
  [note_text9] [varchar](80) NOT NULL,
  [note_text8] [varchar](80) NOT NULL,
  [note_text7] [varchar](80) NOT NULL,
  [note_text6] [varchar](80) NOT NULL,
  [note_text5] [varchar](80) NOT NULL,
  [note_text4] [varchar](80) NOT NULL,
  [note_text3] [varchar](80) NOT NULL,
  [note_text2] [varchar](80) NOT NULL,
  [note_text15] [varchar](80) NOT NULL,
  [note_text14] [varchar](80) NOT NULL,
  [note_text13] [varchar](80) NOT NULL,
  [note_text12] [varchar](80) NOT NULL,
  [note_text11] [varchar](80) NOT NULL,
  [note_text10] [varchar](80) NOT NULL,
  [note_ref_code9] [char](3) NOT NULL,
  [note_ref_code8] [char](3) NOT NULL,
  [note_ref_code7] [char](3) NOT NULL,
  [note_ref_code6] [char](3) NOT NULL,
  [note_ref_code5] [char](3) NOT NULL,
  [note_ref_code4] [char](3) NOT NULL,
  [note_ref_code3] [char](3) NOT NULL,
  [note_ref_code2] [char](3) NOT NULL,
  [note_ref_code15] [char](3) NOT NULL,
  [note_ref_code14] [char](3) NOT NULL,
  [note_ref_code13] [char](3) NOT NULL,
  [note_ref_code12] [char](3) NOT NULL,
  [note_ref_code11] [char](3) NOT NULL,
  [note_ref_code10] [char](3) NOT NULL,
  [epsdt_code] [char](2) NOT NULL,
  [clientvisit_id] [int] NOT NULL
)
ON [PRIMARY]
GO