CREATE TABLE [dbo].[PlannerArchive] (
  [week_of] [smalldatetime] NOT NULL,
  [waitlist_note] [varchar](100) NOT NULL,
  [visittype_id] [smallint] NOT NULL,
  [visit_status] [varchar](15) NOT NULL,
  [status_date] [smalldatetime] NOT NULL,
  [source] [int] NOT NULL,
  [program_id] [smallint] NOT NULL,
  [plannerrecurrence_id] [int] NOT NULL,
  [plannergroup_id] [smallint] NOT NULL,
  [plan_time] [smalldatetime] NOT NULL,
  [plan_id] [int] NOT NULL,
  [plan_date] [smalldatetime] NOT NULL,
  [payment_id] [int] NOT NULL,
  [payer_id] [smallint] NOT NULL,
  [multiple_flag] [bit] NOT NULL,
  [matrix_id] [int] NOT NULL,
  [location_id] [smallint] NOT NULL,
  [is_waitlist] [bit] NOT NULL,
  [is_planned] [bit] NOT NULL,
  [is_forced] [bit] NOT NULL,
  [is_blocked] [bit] NOT NULL,
  [formgroup_id] [smallint] NOT NULL,
  [export_date] [smalldatetime] NOT NULL,
  [emp_id] [smallint] NOT NULL,
  [eligibility_id] [int] NOT NULL,
  [duration] [smallint] NOT NULL,
  [dow] [varchar](5) NOT NULL,
  [date_waitlisted] [datetime] NOT NULL,
  [date_created] [smalldatetime] NOT NULL,
  [clientins_id] [int] NOT NULL,
  [client_id] [int] NOT NULL,
  [by_emp_id] [smallint] NOT NULL,
  [asset_id] [smallint] NOT NULL
)
ON [PRIMARY]
GO