CREATE TABLE [dbo].[ClientMMEFRecord] (
  [OW_cis_client_id] [varchar](15) NULL,
  [Updated_By] [varchar](100) NULL,
  [Updated_At] [datetime] NULL,
  [Created_By] [varchar](100) NULL,
  [Created_At] [datetime] NULL,
  [Record_Status_Id] [int] NULL,
  [Filler] [varchar](40) NULL,
  [Requesting_County] [int] NULL,
  [File_Date] [int] NULL,
  [Card_Issue_Date] [varchar](8) NULL,
  [CMS_ID] [varchar](1) NULL,
  [FFP_ID] [varchar](1) NULL,
  [County_Person_Number] [varchar](2) NULL,
  [County_Fam_Bug_Unit] [varchar](1) NULL,
  [County_S_No] [varchar](7) NULL,
  [County_Aid_Code] [varchar](2) NULL,
  [County_Case_Code] [varchar](2) NULL,
  [Govt_Responsibility] [varchar](1) NULL,
  [CIN] [varchar](9) NULL,
  [EW_Code] [varchar](4) NULL,
  [Beneficiary_Zip_Code] [int] NULL,
  [Beneficiary_State] [varchar](2) NULL,
  [Beneficiary_City] [varchar](20) NULL,
  [Beneficiary_Address2] [varchar](50) NULL,
  [Beneficiary_Address1] [varchar](38) NULL,
  [Beneficiary_Suffix] [varchar](3) NULL,
  [Beneficiary_Middle_Initial] [varchar](1) NULL,
  [Beneficiary_First_Name] [varchar](15) NULL,
  [Beneficiary_Last_Name] [varchar](20) NULL,
  [Case_Name] [varchar](18) NULL,
  [SSN_Verification_Code] [varchar](1) NULL,
  [Primary_Language] [varchar](1) NULL,
  [Ethnicity] [varchar](1) NULL,
  [Gender] [varchar](1) NULL,
  [Birth_Date] [datetime] NULL,
  [HIC_Number_Suffix] [varchar](3) NULL,
  [HIC_Number_SSN] [varchar](9) NULL,
  [Manual_Match_Status] [bit] NULL,
  [Client_ID] [int] NULL,
  [MEDS_Id] [varchar](9) NULL,
  [FileId] [int] NULL,
  [ClientMMEFRecord_ID] [int] NULL
)
ON [PRIMARY]
GO