CREATE TABLE [dbo].[ClientVisitBilling] (
  [soc_obligate_amount] [decimal] NULL,
  [billing_review_status_id] [int] NULL,
  [clientliability_id] [int] NULL,
  [out_of_balance] [bit] NULL,
  [next_payer_id] [smallint] NULL,
  [date_closed] [smalldatetime] NULL,
  [resubmission_claim_id] [int] NULL,
  [patient_resp_amount] [decimal] NULL,
  [pending_adjustment_amount] [decimal] NULL,
  [receipt_code] [varchar](28) NULL,
  [revenue_code] [varchar](28) NULL,
  [rate_override] [bit] NULL,
  [client_age_date] [smalldatetime] NULL,
  [supervising_doctoremp_id] [smallint] NULL,
  [use_supervising_doctor_as_override] [bit] NULL,
  [override_primary] [bit] NULL,
  [last_paid_date] [smalldatetime] NULL,
  [cur_batch_id] [int] NULL,
  [copay_override] [bit] NULL,
  [copay] [decimal] NULL,
  [last_billed] [smalldatetime] NULL,
  [age_date] [smalldatetime] NULL,
  [open_claim] [bit] NULL,
  [balance] [decimal] NULL,
  [other_due] [decimal] NULL,
  [ins_due] [decimal] NULL,
  [client_due] [decimal] NULL,
  [disallowed_amount] [decimal] NULL,
  [adjusted_amount] [decimal] NULL,
  [ins_paid_amount] [decimal] NULL,
  [client_paid_amount] [decimal] NULL,
  [service_amount] [decimal] NULL,
  [next_ins] [bit] NULL,
  [next_clientins_id] [int] NULL,
  [cur_clientins_id] [int] NULL,
  [cur_payer_id] [smallint] NULL,
  [pri_clientins_id] [int] NULL,
  [pri_payer_id] [smallint] NULL,
  [billing_sequence] [tinyint] NULL,
  [billing_ord] [tinyint] NULL,
  [client_id] [int] NULL,
  [clientvisit_id] [int] NULL
)
ON [PRIMARY]
GO