CREATE TABLE [dbo].[OrderLineItem] (
  [consult_physician_id] [smallint] NULL,
  [report_to_send] [varchar](50) NULL,
  [clientaxisdetail_id] [int] NULL,
  [send_to] [varchar](50) NULL,
  [acknowledgement] [varchar](50) NULL,
  [acknowledged_date] [datetime] NULL,
  [internal] [bit] NULL,
  [external_provider_id] [smallint] NULL,
  [orderrecurrencepattern_id] [int] NULL,
  [created_by] [smallint] NULL,
  [orderoutcometype_id] [int] NULL,
  [finished_date] [datetime2] NULL,
  [started_date] [datetime2] NULL,
  [emp_id] [smallint] NULL,
  [episode_id] [int] NULL,
  [due_date] [datetime2] NULL,
  [OrderSetLineId] [int] NULL,
  [OrderSetId] [int] NULL,
  [completed_date] [datetime] NULL,
  [completed_by] [smallint] NULL,
  [type] [varchar](10) NULL,
  [physician_id] [smallint] NULL,
  [completed] [bit] NULL,
  [order_date] [smalldatetime] NULL,
  [skip_pending] [bit] NULL,
  [med_id] [int] NULL,
  [sign_date] [datetime] NULL,
  [sign_by] [smallint] NULL,
  [signed] [bit] NULL,
  [date_updated] [datetime] NULL,
  [updated_by] [smallint] NULL,
  [has_note] [bit] NULL,
  [category] [varchar](50) NULL,
  [discontinued_by] [smallint] NULL,
  [discontinued_date] [datetime] NULL,
  [discontinued] [bit] NULL,
  [order_id] [int] NULL,
  [orderlineitem_id] [int] NULL
)
ON [PRIMARY]
GO