CREATE TABLE [dbo].[CrediblePlanView] (
  [date_updated] [datetime] NULL,
  [updatedby_emp_id] [smallint] NULL,
  [date_created] [datetime] NULL,
  [createdby_emp_id] [smallint] NULL,
  [external_id_3] [varchar](12) NULL,
  [external_id_2] [varchar](12) NULL,
  [external_id_1] [varchar](12) NULL,
  [long_common_name] [nvarchar](255) NULL,
  [snomed_fsn] [varchar](900) NULL,
  [deleted] [bit] NULL,
  [free_text_documentation] [bit] NULL,
  [priority_level] [tinyint] NULL,
  [element_status] [bit] NULL,
  [goal_achievement_status] [bit] NULL,
  [end_date] [bit] NULL,
  [target_date] [bit] NULL,
  [start_date] [bit] NULL,
  [color] [varchar](25) NULL,
  [external_code] [varchar](12) NULL,
  [loinc_num] [nvarchar](7) NULL,
  [snomed_cid] [bigint] NULL,
  [tooltip] [varchar](50) NULL,
  [label] [varchar](100) NULL,
  [customElement_id] [int] NULL,
  [bedboardFacility_id] [varchar](1) NULL,
  [next_review_days] [varchar](1) NULL,
  [nextReviewDate] [varchar](1) NULL,
  [planType_id] [varchar](1) NULL,
  [goal_percentage] [varchar](1) NULL,
  [goal_completed] [varchar](1) NULL,
  [alteredPlan_planExpirationDate] [varchar](1) NULL,
  [use_methods] [varchar](1) NULL,
  [bedboardWing_id] [varchar](1) NULL,
  [ruleSet_id] [varchar](1) NULL,
  [clientvisit_id] [varchar](1) NULL,
  [client_id] [varchar](1) NULL
)
ON [PRIMARY]
GO