CREATE TABLE [dbo].[Component] (
  [wiley_id] [int] NOT NULL,
  [updatedby_emp_id] [smallint] NOT NULL,
  [tooltip] [varchar](50) NOT NULL,
  [title] [varchar](500) NOT NULL,
  [target_date] [smalldatetime] NOT NULL,
  [start_date] [smalldatetime] NOT NULL,
  [snomed_fsn] [varchar](900) NOT NULL,
  [snomed_cid] [bigint] NOT NULL,
  [priority_status] [int] NOT NULL,
  [previous_component_id] [int] NOT NULL,
  [parent_id] [int] NOT NULL,
  [order] [smallint] NOT NULL,
  [loinc_code] [nvarchar](7) NOT NULL,
  [label] [varchar](100) NOT NULL,
  [has_targetdate] [bit] NOT NULL,
  [has_startdate] [bit] NOT NULL,
  [has_goalachievement_status] [bit] NOT NULL,
  [has_enddate] [bit] NOT NULL,
  [has_element_status] [bit] NOT NULL,
  [has_children] [bit] NOT NULL,
  [goalachievement_date] [datetime] NOT NULL,
  [free_text_documentation] [bit] NOT NULL,
  [end_date] [smalldatetime] NOT NULL,
  [employee_priority_status] [int] NOT NULL,
  [date_updated] [datetime] NOT NULL,
  [date_created] [datetime] NOT NULL,
  [credibleplan_id] [int] NOT NULL,
  [component_type_id] [int] NOT NULL,
  [color] [varchar](25) NOT NULL,
  [client_priority_status] [int] NOT NULL,
  [child_label] [varchar](100) NOT NULL,
  [allow_signatures] [bit] NOT NULL,
  [active] [bit] NOT NULL
)
ON [PRIMARY]
GO