CREATE TABLE [dbo].[Z_834_L2310_Provider_Info] (
  [code5_end] [char](1) NULL,
  [maintenance_reason] [char](3) NULL,
  [temp2] [char](1) NULL,
  [provider_effective_dt] [varchar](8) NULL,
  [entity_id] [char](2) NULL,
  [action_code] [char](1) NULL,
  [code5] [char](3) NULL,
  [code4_end] [char](1) NULL,
  [contact_number3] [varchar](80) NULL,
  [contact_qual3] [char](2) NULL,
  [contact_number2] [varchar](80) NULL,
  [contact_qual2] [char](2) NULL,
  [contact_number] [varchar](80) NULL,
  [contact_qual] [char](2) NULL,
  [temp1] [char](1) NULL,
  [contact_function] [char](2) NULL,
  [code4] [char](3) NULL,
  [code3_end] [char](1) NULL,
  [location_id] [varchar](30) NULL,
  [location_qual] [char](2) NULL,
  [country] [char](3) NULL,
  [zip] [varchar](15) NULL,
  [state] [char](2) NULL,
  [city] [varchar](30) NULL,
  [code3] [char](2) NULL,
  [code2_end] [char](1) NULL,
  [entity_relationship] [char](2) NULL,
  [id_code] [varchar](80) NULL,
  [id_code_qual] [char](2) NULL,
  [suffix] [varchar](10) NULL,
  [prefix] [varchar](10) NULL,
  [middlename] [varchar](25) NULL,
  [firstname] [varchar](25) NULL,
  [lastname_or_orgname] [varchar](35) NULL,
  [entity_type_qual] [char](1) NULL,
  [entity_id_code] [char](2) NULL,
  [code2] [char](3) NULL,
  [code1_end] [char](1) NULL,
  [assigned_num] [int] NULL,
  [code1] [char](2) NULL,
  [l2000_id] [int] NULL,
  [batch_id] [int] NULL,
  [l2310_id] [int] NULL
)
ON [PRIMARY]
GO