CREATE TABLE [dbo].[EmpVisit] (
  [visitguid] [varchar](50) NOT NULL,
  [visit_dateday] [int] NOT NULL,
  [transfer_date] [smalldatetime] NOT NULL,
  [timeout_utc] [datetime2] NOT NULL,
  [timein_utc] [datetime2] NOT NULL,
  [status] [varchar](20) NOT NULL,
  [source] [char](1) NOT NULL,
  [signature_datetime] [smalldatetime] NOT NULL,
  [signature_cnt] [tinyint] NOT NULL,
  [reviewer_comment] [varchar](255) NOT NULL,
  [rev_timeout_utc] [datetime2] NOT NULL,
  [rev_timein_utc] [datetime2] NOT NULL,
  [rem_address] [varchar](50) NOT NULL,
  [is_readonly] [bit] NOT NULL,
  [handheld_version] [varchar](50) NOT NULL,
  [form_ver_id] [int] NOT NULL,
  [for_emp_id] [smallint] NOT NULL,
  [empvisittype_id] [smallint] NOT NULL,
  [empvisit_id] [int] NOT NULL,
  [emplastname] [varchar](50) NOT NULL,
  [empfirstname] [varchar](50) NOT NULL,
  [emp_name] [varchar](75) NOT NULL,
  [duration] [smallint] NOT NULL,
  [date2] [smalldatetime] NOT NULL,
  [date1] [smalldatetime] NOT NULL,
  [date_updated] [smalldatetime] NOT NULL,
  [date_created] [smalldatetime] NOT NULL,
  [by_emp_id] [smallint] NOT NULL,
  [appr_user] [varchar](50) NOT NULL,
  [appr_date_utc] [datetime2] NOT NULL
)
ON [PRIMARY]
GO