CREATE TABLE [dbo].[Z_EDI_L2420C_Service_Facility] (
  [zip] [varchar](15) NOT NULL,
  [suffix] [varchar](10) NOT NULL,
  [state] [char](2) NOT NULL,
  [service_location_additional_id2] [varchar](50) NOT NULL,
  [reference_id_qual2] [char](3) NOT NULL,
  [prefix] [varchar](10) NOT NULL,
  [middle_name] [varchar](25) NOT NULL,
  [location_qual] [char](1) NOT NULL,
  [location_id] [char](1) NOT NULL,
  [last_name_or_org] [varchar](60) NOT NULL,
  [l2420C_id] [int] NOT NULL,
  [l2400_id] [int] NOT NULL,
  [id_code_qual] [varchar](2) NOT NULL,
  [first_name] [varchar](35) NOT NULL,
  [entity_type_qual] [char](1) NOT NULL,
  [entity_id_code] [char](3) NOT NULL,
  [country_sub_code] [char](3) NOT NULL,
  [country_code] [char](3) NOT NULL,
  [code5_end] [char](1) NOT NULL,
  [code4_end] [char](1) NOT NULL,
  [code3_end] [char](1) NOT NULL,
  [code2_end] [char](1) NOT NULL,
  [code1_end] [char](1) NOT NULL,
  [city] [varchar](30) NOT NULL,
  [batch_id] [int] NOT NULL,
  [address_info2] [varchar](55) NOT NULL
)
ON [PRIMARY]
GO