CREATE TABLE [dbo].[EmpVisit] (
  [rev_timeout_utc] [datetime2] NULL,
  [rev_timein_utc] [datetime2] NULL,
  [timeout_utc] [datetime2] NULL,
  [timein_utc] [datetime2] NULL,
  [appr_date_utc] [datetime2] NULL,
  [date2] [smalldatetime] NULL,
  [date1] [smalldatetime] NULL,
  [date_updated] [smalldatetime] NULL,
  [date_created] [smalldatetime] NULL,
  [handheld_version] [varchar](50) NULL,
  [is_readonly] [bit] NULL,
  [signature_cnt] [tinyint] NULL,
  [signature_datetime] [smalldatetime] NULL,
  [source] [char](1) NULL,
  [form_ver_id] [int] NULL,
  [visitguid] [varchar](50) NULL,
  [visit_dateday] [int] NULL,
  [rev_timeout] [smalldatetime] NULL,
  [rev_timein] [smalldatetime] NULL,
  [reviewer_comment] [varchar](255) NULL,
  [rem_address] [varchar](50) NULL,
  [transfer_date] [smalldatetime] NULL,
  [appr_user] [varchar](50) NULL,
  [appr_date] [smalldatetime] NULL,
  [appr] [bit] NULL,
  [duration] [smallint] NULL,
  [timeout] [smalldatetime] NULL,
  [timein] [smalldatetime] NULL,
  [status] [varchar](20) NULL,
  [emp_name] [varchar](75) NULL,
  [emplastname] [varchar](50) NULL,
  [empfirstname] [varchar](50) NULL,
  [empvisittype] [varchar](20) NULL,
  [empvisittype_id] [smallint] NULL,
  [by_emp_id] [smallint] NULL,
  [emp_id] [smallint] NULL,
  [for_emp_id] [smallint] NULL,
  [empvisit_id] [int] NULL
)
ON [PRIMARY]
GO