CREATE TABLE [dbo].[ImportELabs] (
  [test_description] [varchar](255) NULL,
  [LOINC_code] [varchar](7) NULL,
  [facility_id_r] [int] NULL,
  [panic_flag_r] [varchar](50) NULL,
  [range_r] [varchar](50) NULL,
  [units_r] [varchar](50) NULL,
  [abnormal_flag_r] [varchar](50) NULL,
  [abnormal_r] [varchar](50) NULL,
  [result_date_r] [varchar](50) NULL,
  [status_r] [varchar](50) NULL,
  [result_value_r] [varchar](50) NULL,
  [test_type_p] [varchar](50) NULL,
  [specimen_condition_p] [varchar](200) NULL,
  [specimen_source_p] [varchar](200) NULL,
  [action_code_p] [varchar](50) NULL,
  [additional_info_p] [varchar](500) NULL,
  [status_p] [varchar](50) NULL,
  [result_date_p] [datetime] NULL,
  [received_date_p] [datetime] NULL,
  [collection_date_p] [datetime] NULL,
  [resultat] [datetime] NULL,
  [collectedat] [datetime] NULL,
  [manual_entry] [bit] NULL,
  [fasting] [varchar](50) NULL,
  [status] [varchar](50) NULL,
  [sender_order_number] [varchar](50) NULL,
  [place_order_number] [varchar](50) NULL,
  [emp_id] [int] NULL,
  [client_id] [int] NULL,
  [report_id] [int] NULL,
  [procedure_id] [int] NULL,
  [accession_id] [int] NULL
)
ON [PRIMARY]
GO