CREATE TABLE [dbo].[ClientMMEFData] (
  [HCP_Code_3] [varchar](3) NULL,
  [HCP_Status_3] [varchar](2) NULL,
  [HCP_Code_2] [varchar](3) NULL,
  [HCP_Status_2] [varchar](2) NULL,
  [Special_Program_Eligibility_3] [varchar](3) NULL,
  [Special_Program_County_3] [varchar](2) NULL,
  [Special_Program_AID_3] [varchar](2) NULL,
  [HF_In_Out] [varchar](4) NULL,
  [Special_Obligation] [int] NULL,
  [Special_Program_Eligibility_2] [varchar](3) NULL,
  [Special_Program_County_2] [varchar](2) NULL,
  [Special_Program_AID_2] [varchar](2) NULL,
  [Special_Program_Eligibility_1] [varchar](3) NULL,
  [Special_Program_County_1] [varchar](2) NULL,
  [Special_Program_AID_1] [varchar](2) NULL,
  [SURS_Code] [varchar](3) NULL,
  [OHC] [varchar](1) NULL,
  [HCP_Code_1] [varchar](3) NULL,
  [HCP_Status_1] [varchar](2) NULL,
  [Filler] [varchar](10) NULL,
  [TypeID] [varchar](2) NULL,
  [Plan_ID] [varchar](3) NULL,
  [Source_ID] [varchar](5) NULL,
  [Carrier_Code] [varchar](4) NULL,
  [Medicare_Status] [varchar](3) NULL,
  [Share_Cost_Amount] [int] NULL,
  [Eligibility_Status] [varchar](3) NULL,
  [Resident_County] [varchar](2) NULL,
  [County_Responsibility] [varchar](2) NULL,
  [Aid_Code] [varchar](2) NULL,
  [Eligibility_Month] [varchar](2) NULL,
  [Eligibility_Year] [varchar](4) NULL,
  [Month_no] [int] NULL,
  [clientMMEFRecord_ID] [int] NULL,
  [ClientMMEFData_ID] [int] NULL
)
ON [PRIMARY]
GO