CREATE TABLE [dbo].[StateReportConfigurations] (
  [DefaultFileName] [nvarchar](300) NULL,
  [UseRowSecurity] [bit] NULL,
  [IsRunning] [bit] NULL,
  [FormType] [int] NULL,
  [RequireWSAuth] [bit] NULL,
  [ColToUpdate] [varchar](25) NULL,
  [IsAdvsearch] [bit] NULL,
  [PrimaryKey] [varchar](50) NULL,
  [IsDDTable] [bit] NULL,
  [ExportTableNum] [int] NULL,
  [ClearExportTable] [bit] NULL,
  [IsEmpForm] [bit] NULL,
  [FormVersionId] [int] NULL,
  [FormName] [varchar](50) NULL,
  [FormId] [smallint] NULL,
  [UniqueKey] [varchar](25) NULL,
  [AllowDelete] [bit] NULL,
  [Notes] [varchar](max) NULL,
  [edi_config_id] [smallint] NULL,
  [IsLocked] [bit] NULL,
  [ModifiedBy] [int] NULL,
  [ModifiedOn] [smalldatetime] NULL,
  [CreatedBy] [int] NULL,
  [CreatedOn] [smalldatetime] NULL,
  [CustomReport] [varchar](50) NULL,
  [LastRun] [smalldatetime] NULL,
  [StoredProcedureName] [varchar](max) NULL,
  [WhereClause] [varchar](max) NULL,
  [PreQuery] [varchar](max) NULL,
  [DateFormat] [varchar](20) NULL,
  [ForPrint] [bit] NULL,
  [BatchMode] [bit] NULL,
  [QuotedFields] [bit] NULL,
  [Delimiter] [varchar](3) NULL,
  [OutputFormat] [varchar](5) NULL,
  [Name] [varchar](50) NULL,
  [StateReportConfigurationId] [int] NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO