CREATE TABLE [dbo].[ContactsHistory] (
  [mobile_visit_dest_address] [bit] NULL,
  [contact_fax] [varchar](25) NULL,
  [source] [varchar](10) NULL,
  [agency_id] [smallint] NULL,
  [contact_address2] [varchar](150) NULL,
  [info_release_start] [smalldatetime] NULL,
  [updatedby_emp_id] [smallint] NULL,
  [date_updated] [smalldatetime] NULL,
  [date_created] [smalldatetime] NULL,
  [info_release_expire] [datetime] NULL,
  [info_release] [bit] NULL,
  [visit_map_group] [tinyint] NULL,
  [clientvisit_id] [int] NULL,
  [external_id] [varchar](12) NULL,
  [relationship] [varchar](50) NULL,
  [contact_email] [varchar](50) NULL,
  [contact_mobile_phone] [varchar](25) NULL,
  [contact_alt_phone] [varchar](25) NULL,
  [contact_phone] [varchar](25) NULL,
  [contact_zip] [varchar](10) NULL,
  [contact_state] [char](3) NULL,
  [contact_city] [varchar](50) NULL,
  [contact_address] [varchar](150) NULL,
  [contact_name] [varchar](65) NULL,
  [contacttype_id] [smallint] NULL,
  [client_id] [int] NULL,
  [contact_id] [int] NULL
)
ON [PRIMARY]
GO