CREATE TABLE [dbo].[Programs] (
  [discountgroup_id] [int] NULL,
  [aggregator_id] [int] NULL,
  [is_mapped] [bit] NULL,
  [Is_42CFR_CC] [bit] NULL,
  [demonstration_project_id] [varchar](50) NULL,
  [send_to_hie] [bit] NULL,
  [payer_plantype_id] [int] NULL,
  [DimensionId] [int] NULL,
  [match_on_datetime] [bit] NULL,
  [is_residential] [bit] NULL,
  [is_private] [bit] NULL,
  [require_insurance_for_planner] [bit] NULL,
  [parentonlyforepisode] [bit] NULL,
  [core_service_code] [varchar](12) NULL,
  [export_program_code] [varchar](12) NULL,
  [parent_program_id] [smallint] NULL,
  [is_parent] [bit] NULL,
  [updatedby_emp_id] [smallint] NULL,
  [createdby_emp_id] [smallint] NULL,
  [date_updated] [smalldatetime] NULL,
  [date_created] [smalldatetime] NULL,
  [location_number] [varchar](50) NULL,
  [deleted] [bit] NULL,
  [flag_inactive_days] [smallint] NULL,
  [txplan_end_days] [smallint] NULL,
  [redx_formgroup_id] [smallint] NULL,
  [authexceedx] [bit] NULL,
  [has_roles] [bit] NULL,
  [program_group] [varchar](12) NULL,
  [revenue_code] [varchar](20) NULL,
  [external_code] [varchar](25) NULL,
  [default_location_id] [smallint] NULL,
  [program_desc] [varchar](50) NULL,
  [program_code] [varchar](10) NULL,
  [program_id] [smallint] NULL
)
ON [PRIMARY]
GO