CREATE TABLE [dbo].[NotificationTablesView] (
  [updatedby_emp_id] [smallint] NOT NULL,
  [type] [char](1) NOT NULL,
  [specifyname6] [varchar](50) NOT NULL,
  [specifyname5] [varchar](50) NOT NULL,
  [specifyname4] [varchar](50) NOT NULL,
  [specifyname3] [varchar](50) NOT NULL,
  [specifyname2] [varchar](50) NOT NULL,
  [specifylabel6] [varchar](50) NOT NULL,
  [specifylabel5] [varchar](50) NOT NULL,
  [specifylabel4] [varchar](50) NOT NULL,
  [specifylabel3] [varchar](50) NOT NULL,
  [specifylabel2] [varchar](50) NOT NULL,
  [specifyid6] [varchar](50) NOT NULL,
  [specifyid5] [varchar](50) NOT NULL,
  [specifyid4] [varchar](50) NOT NULL,
  [specifyid3] [varchar](50) NOT NULL,
  [specifyid2] [varchar](50) NOT NULL,
  [notificationtrigger_id] [smallint] NOT NULL,
  [description] [varchar](50) NOT NULL,
  [date_updated] [smalldatetime] NOT NULL,
  [can_specify_id6] [bit] NOT NULL,
  [can_specify_id5] [bit] NOT NULL,
  [can_specify_id4] [bit] NOT NULL,
  [can_specify_id3] [bit] NOT NULL,
  [can_specify_id2] [bit] NOT NULL,
  [can_be_specific] [bit] NOT NULL,
  [reminder_date] [smalldatetime] NOT NULL,
  [title] [varchar](150) NOT NULL,
  [is_trigger] [bit] NOT NULL,
  [notificationevent_id] [int] NOT NULL,
  [dismissed] [bit] NOT NULL,
  [clientvisit_id] [int] NOT NULL
)
ON [PRIMARY]
GO