CREATE TABLE [dbo].[SureScriptsMedHistory] (
  [TransactionId] [char](32) NULL,
  [diagnosis_code_qualifier] [varchar](20) NULL,
  [diagnosis_code_value] [varchar](20) NULL,
  [payer_name] [varchar](50) NULL,
  [payer_id] [varchar](50) NULL,
  [date_updated] [datetime] NULL,
  [prescriber_zipcode] [varchar](10) NULL,
  [prescriber_state] [varchar](2) NULL,
  [prescriber_city] [varchar](50) NULL,
  [prescriber_address_2] [varchar](200) NULL,
  [prescriber_address_1] [varchar](200) NULL,
  [prescriber_middle_name] [varchar](100) NULL,
  [prescriber_first_name] [varchar](100) NULL,
  [prescriber_last_name] [varchar](100) NULL,
  [prescriber_dea] [varchar](9) NULL,
  [prescriber_npi] [varchar](50) NULL,
  [pharmacy_phone_2] [varchar](50) NULL,
  [pharmacy_fax] [varchar](50) NULL,
  [pharmacy_phone] [varchar](50) NULL,
  [pharmacy_zipcode] [varchar](10) NULL,
  [pharmacy_state] [varchar](2) NULL,
  [pharmacy_city] [varchar](50) NULL,
  [pharmacy_address_2] [varchar](200) NULL,
  [pharmacy_address_1] [varchar](200) NULL,
  [pharmacy_store_name] [varchar](150) NULL,
  [pharmacy_ncpdpid] [varchar](50) NULL,
  [last_filled] [datetime] NULL,
  [dayssupply] [varchar](12) NULL,
  [quantity_codelist_qual] [varchar](4) NULL,
  [quantity_value] [varchar](25) NULL,
  [quantity_qual] [varchar](4) NULL,
  [drug_code] [varchar](20) NULL,
  [drug_code_qual] [varchar](4) NULL,
  [drug_description] [varchar](300) NULL,
  [fdb_medid] [varchar](20) NULL,
  [client_id] [int] NULL,
  [surescripts_med_history_id] [int] NULL
)
ON [PRIMARY]
GO