CREATE TABLE [dbo].[MedAdminSchedule] (
  [VisitTempId] [int] NOT NULL,
  [UpdatedDate] [datetime] NOT NULL,
  [UpdatedByEmpId] [smallint] NOT NULL,
  [UnusedMedReason] [int] NOT NULL,
  [UnusedMedCount] [decimal] NOT NULL,
  [Suspended] [bit] NOT NULL,
  [Stat] [bit] NOT NULL,
  [RouteTime] [nvarchar](100) NOT NULL,
  [RefusalReason] [varchar](100) NOT NULL,
  [RefillCount] [decimal] NOT NULL,
  [QuantityAdministered] [decimal] NOT NULL,
  [PrnInterval] [tinyint] NOT NULL,
  [PillCount] [decimal] NOT NULL,
  [PatientResponseId] [int] NOT NULL,
  [MedScheduleRecurrenceId] [int] NOT NULL,
  [MedScheduleDesignId] [int] NOT NULL,
  [MedInventoryId] [int] NOT NULL,
  [MedId] [int] NOT NULL,
  [MedAdminScheduleId] [int] NOT NULL,
  [MedAdminReconciliationId] [int] NOT NULL,
  [InjectionSite] [varchar](50) NOT NULL,
  [Frequency] [nvarchar](100) NOT NULL,
  [ExternalId] [varchar](50) NOT NULL,
  [EmarPillboxId] [int] NOT NULL,
  [DosageNote] [varchar](500) NOT NULL,
  [DosageAction] [varchar](50) NOT NULL,
  [DispenseOn] [datetime] NOT NULL,
  [DispensedVerifiedByEmpId] [smallint] NOT NULL,
  [DispensedOn] [datetime] NOT NULL,
  [DispensedByEmpId] [smallint] NOT NULL,
  [DidPatientTake] [bit] NOT NULL,
  [DatePillboxReconciled] [datetime] NOT NULL,
  [CreatedByEmpId] [smallint] NOT NULL,
  [CreateDate] [datetime] NOT NULL
)
ON [PRIMARY]
GO