CREATE TABLE [dbo].[SmoothIntervalsHistory] (
  [interval_number] [bigint] NULL,
  [wing_desc] [varchar](50) NULL,
  [bedboardwing_id] [smallint] NULL,
  [facility_type] [varchar](25) NULL,
  [facility_desc] [varchar](50) NULL,
  [bedboardfacility_id] [smallint] NULL,
  [is_restraintseclusion] [bit] NULL,
  [room_desc] [varchar](20) NULL,
  [bedboardroom_id] [smallint] NULL,
  [status] [varchar](12) NULL,
  [bed_desc] [varchar](20) NULL,
  [bedboardbed_id] [smallint] NULL,
  [releasebed] [bit] NULL,
  [est_release_date_interval] [smalldatetime] NULL,
  [admission_date_interval] [smalldatetime] NULL,
  [interval_team_id] [smallint] NULL,
  [date_created_interval] [datetime2] NULL,
  [timeout] [smalldatetime] NULL,
  [timein] [smalldatetime] NULL,
  [clientbedboardinterval_id] [int] NULL,
  [clientbedboard_team_id] [smallint] NULL,
  [est_release_date] [smalldatetime] NULL,
  [release_date] [smalldatetime] NULL,
  [admission_date] [smalldatetime] NULL,
  [clientbedboard_id] [int] NULL,
  [client_status] [varchar](10) NULL,
  [age] [int] NULL,
  [sex] [varchar](1) NULL,
  [dob] [datetime] NULL,
  [last_name] [varchar](40) NULL,
  [first_name] [varchar](35) NULL,
  [client_id] [int] NULL
)
ON [PRIMARY]
GO